- .github/workflows/build.yml
- api/Dockerfile
- api/home/for/data_sources/ForecastDS-azure.json
- docker-compose.yml
- radixconfig.yaml
- web/Dockerfile
- Github Actions to build and push images to mariner.acr.io/for/*
- Github Action to deploy master branch to Radix
- radixconfig.yaml file
> Deploy to radix

- .gitignore
- docker-compose.yml
wrong port used in docker-compose file, application did not start
> update port used

- docker-compose.yml
- radixconfig.yaml
- web/Dockerfile
- web/custom-plugins/for-operations/src/components/EditOperation.tsx
- web/custom-plugins/for-operations/src/components/OperationsTable.tsx
- web/custom-plugins/for-operations/src/components/SelectLocation.tsx
- web/custom-plugins/for-operations/src/components/SelectModel.tsx
- web/custom-plugins/forecast-of-response/src/hooks/useSearch.tsx
enable auth for FoR and update API calls to match the updates in DMT
> Enable auth

- .gitignore
- docker-compose.yml
- web/custom-plugins/forecast-of-response/package.json
- web/custom-plugins/forecast-of-response/src/Enums.ts
- web/custom-plugins/forecast-of-response/src/Icons.ts
- web/custom-plugins/forecast-of-response/src/Types.ts
- web/custom-plugins/forecast-of-response/src/components/AccessControl/AccessControlList.tsx
- web/custom-plugins/forecast-of-response/src/components/Dashboard.tsx
- web/custom-plugins/forecast-of-response/tsconfig.json
- EDS styled component for viewing and editing DMSS ACL
- Not actually connected to DMSS. Waiting for other branches to merge.
> ACL component

- web/custom-plugins/forecast-of-response/src/Pages/OperationCreate.tsx
- web/custom-plugins/forecast-of-response/src/Pages/OperationView.tsx
- web/custom-plugins/forecast-of-response/src/components/DateRangePicker.tsx
- web/custom-plugins/forecast-of-response/src/components/Map.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/SelectConfig.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/SelectLocation.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/SelectSTask.tsx
- Overall more consistent styling on "create operation"
- Can now select location by clicking on map
- OperationDetails now renders even when operation has no phases
closes #52
> create operation - styling, loc from map, bugs

- web/custom-plugins/forecast-of-response/package.json
- web/custom-plugins/forecast-of-response/src/Pages/Dashboard.tsx
- web/custom-plugins/forecast-of-response/src/Pages/OperationOverview.tsx
- web/custom-plugins/forecast-of-response/src/components/App/Menu.tsx
- web/custom-plugins/forecast-of-response/yarn.lock
* add icon to all elements in left menu and remove create operation link
* store the value for the collapsed menu state in the react router location object
* remove some duplicate packages from pcakage.json that are defined in dmt (i think this is what caused the collapse bug)
closes #66
> update menu behavior

- api/home/for/data/ForecastDS/ForecastOfResponse/Blueprints/Operation.json
- api/home/for/data/ForecastDS/ForecastOfResponse/Operations/operation1.json
- api/home/for/data/ForecastDS/ForecastOfResponse/SIMACompute/compute.yml
- web/custom-plugins/forecast-of-response/src/Pages/OperationCreate.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/SelectSIMACompute.tsx
- Added "SIMAComputeConnectInfo" Blob type on the Operation  root
- Updated "Create Operation" to include a compute.yml file
closes #94
> feature: upload a sima compute.yaml to operation

- api/home/for/data/ForecastDS/FoR-BP/Blueprints/Simulation.json
- api/home/for/data/ForecastDS/FoR-Data/Operations/operation1.json
- api/home/for/data/ForecastDS/FoR-Data/Results/fullExample.json
- web/custom-plugins/forecast-of-response/src/components/Operations/PhaseView.tsx
- Update reference to Blueprint for ResultFile
> Fix invalid blueprint path for ResultFile in attributeType/type

- web/custom-plugins/forecast-of-response/src/App.tsx
- web/custom-plugins/forecast-of-response/src/Pages/Dashboard.tsx
- web/custom-plugins/forecast-of-response/src/Pages/OperationCreate.tsx
- web/custom-plugins/forecast-of-response/src/Pages/OperationOverview.tsx
- web/custom-plugins/forecast-of-response/src/components/App/Content.tsx
- web/custom-plugins/forecast-of-response/src/components/App/Header.tsx
- web/custom-plugins/forecast-of-response/src/components/App/Menu.css
- web/custom-plugins/forecast-of-response/src/components/App/Menu.tsx
- web/custom-plugins/forecast-of-response/src/components/Comments.tsx
- web/custom-plugins/forecast-of-response/src/components/Design/Icons.ts
- web/custom-plugins/forecast-of-response/src/components/Map.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/OperationDetails.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/PhaseView.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/SelectLocation.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/SelectSIMACompute.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/SelectSTask.tsx
a bunch of small fixes
Also, improve functionality for selecting location in "create new operation" .
need to pull latest dmt/web image to make access control list work
closes #130 
closes #132 
closes #129 
closes #131 
closes #134
closes #136
closes #137
closes #138
> some fixes

- web/custom-plugins/forecast-of-response/src/App.tsx
- web/custom-plugins/forecast-of-response/src/Pages/Dashboard.tsx
- web/custom-plugins/forecast-of-response/src/Pages/OperationCreate.tsx
- web/custom-plugins/forecast-of-response/src/Pages/OperationOverview.tsx
- web/custom-plugins/forecast-of-response/src/components/App/Content.tsx
- web/custom-plugins/forecast-of-response/src/components/App/Header.tsx
- web/custom-plugins/forecast-of-response/src/components/App/Menu.css
- web/custom-plugins/forecast-of-response/src/components/App/Menu.tsx
- web/custom-plugins/forecast-of-response/src/components/Comments.tsx
- web/custom-plugins/forecast-of-response/src/components/Design/Icons.ts
- web/custom-plugins/forecast-of-response/src/components/Map.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/OperationDetails.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/PhaseView.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/SelectLocation.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/SelectSIMACompute.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/SelectSTask.tsx
a bunch of small fixes
Also, improve functionality for selecting location in "create new operation" .
need to pull latest dmt/web image to make access control list work
closes #130 
closes #132 
closes #129 
closes #131 
closes #134
closes #136
closes #137
closes #138
> Various fixes

- web/custom-plugins/forecast-of-response/src/components/Operations/SelectSIMACompute.tsx
> bugfix: yaml reading fails

- web/custom-plugins/forecast-of-response/src/components/Operations/OperationDetails.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/PhaseView.tsx
- web/custom-plugins/forecast-of-response/src/components/Result.tsx
fix bug: don't show Result when _id is undefined
> fix bug: result in phase view

- web/custom-plugins/forecast-of-response/src/Pages/OperationCreate.tsx
- web/custom-plugins/forecast-of-response/src/Pages/OperationView.tsx
- web/custom-plugins/forecast-of-response/src/components/Comments.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/PhaseView.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/SelectConfig.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/SelectLocation.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/SelectSIMACompute.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/SelectSTask.tsx
* improve error handling on the create new opeartion page
closes #156 
closes #157 
closes #158 
closes #159
> more UI improvements

- web/custom-plugins/forecast-of-response/src/components/Operations/PhaseView.tsx
- web/custom-plugins/forecast-of-response/src/components/ReoccurringJob.tsx
hourly interval option for CronJobs - allow step values
closes #171
> feat: hourly cronjob steps

- api/home/DMT/data/DMT-Internal/DMT/Jobs/Container.json
- web/custom-plugins/forecast-of-response/src/Pages/OperationCreate.tsx
- web/custom-plugins/forecast-of-response/src/Types.ts
- web/custom-plugins/forecast-of-response/src/components/Design/Icons.ts
- web/custom-plugins/forecast-of-response/src/components/Jobs.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/PhaseView.tsx
- web/custom-plugins/forecast-of-response/src/components/Result.tsx
- web/custom-plugins/forecast-of-response/src/const.ts
- web/custom-plugins/forecast-of-response/src/utils/createContainerJob.ts
- Label for jobs (set date time on creation)
- More icons on buttons
- New Locations and Configs uses separate sub packages.
closes #181 closes #180 closes #176
> Job labels

- web/custom-plugins/forecast-of-response/src/Types.ts
- web/custom-plugins/forecast-of-response/src/components/Operations/OperatorPhaseView.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/PhaseView.tsx
- web/custom-plugins/forecast-of-response/src/components/Result.tsx
- web/custom-plugins/forecast-of-response/src/utils/sort.tsx
update the view for the operator
* also, for the result compoent, reset the plot when selected result changes
closes #177
> update operator phase view and fix bug for phase view

- api/home/for/data/ForecastDS/FoR-Data/Comments/SverdrupAnchorReplace2021Comments.json
- web/custom-plugins/forecast-of-response/src/Pages/Dashboard.tsx
search for Comments, not Comment. Unpack and sort
> search for Comments, not Comment. Unpack and sort

- web/custom-plugins/forecast-of-response/src/components/Plots/LinesOverTime.tsx
- web/custom-plugins/forecast-of-response/src/components/Result.tsx
fix bug where page crashes when changing between plot runs
closes #192
> bugfix: update states of plot selection boxes correctly.

- api/home/for/data/ForecastDS/FoR-BP/Blueprints/Graph.json
- api/home/for/data/ForecastDS/FoR-BP/Blueprints/PlotState.json
- api/home/for/data/ForecastDS/FoR-BP/Blueprints/SimulationConfig.json
- api/home/for/data/ForecastDS/FoR-Data/Operations/operation1.json
- web/custom-plugins/forecast-of-response/src/Enums.ts
- web/custom-plugins/forecast-of-response/src/Types.ts
- web/custom-plugins/forecast-of-response/src/components/CustomScrim.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/PhaseView.tsx
- web/custom-plugins/forecast-of-response/src/components/Result.tsx
> Stored plots and graphs

- api/home/for/data/ForecastDS/FoR-Data/Operations/operation1.json
- web/custom-plugins/forecast-of-response/src/components/Operations/PhaseView.tsx
- web/custom-plugins/forecast-of-response/src/components/Result.tsx
Fix plots not working:
- save
- add graph
- load from example operation
> Hotfix: Stored plots

- web/custom-plugins/forecast-of-response/src/components/Operations/PhaseView.tsx
- web/custom-plugins/forecast-of-response/src/components/Plots/ArrowPlots.tsx
> fix using wrong loading state. Rotate wave arrows in plot 180deg

- api/home/for/data/ForecastDS/FoR-Data/Comments/SverdrupAnchorReplace2021Comments.json
- web/custom-plugins/forecast-of-response/package.json
- web/custom-plugins/forecast-of-response/src/Pages/Dashboard.tsx
- web/custom-plugins/forecast-of-response/src/components/Design/markercluster.css
- web/custom-plugins/forecast-of-response/yarn.lock
> add marker cluster to dashboard

- web/custom-plugins/forecast-of-response/src/components/Design/Colors.ts
- web/custom-plugins/forecast-of-response/src/components/Plots/ArrowPlots.tsx
- web/custom-plugins/forecast-of-response/src/components/Plots/LinesOverTime.tsx
- web/custom-plugins/forecast-of-response/src/components/Result.tsx
* add more colors
* if index for plot colors go out of bounds, use black color
closes #191
> add function to get color

- web/custom-plugins/forecast-of-response/src/components/Operations/PhaseView.tsx
- web/custom-plugins/forecast-of-response/src/components/Result.tsx
- web/custom-plugins/forecast-of-response/src/utils/sort.tsx
* display newest result first in the list
* reload data in plot window when selected result changes
closes #213 
closes #214
> sort results adn reset plot correctly

- web/custom-plugins/forecast-of-response/package.json
- web/custom-plugins/forecast-of-response/src/components/Operations/OperatorPhaseView.tsx
- web/custom-plugins/forecast-of-response/src/components/Operations/PhaseView.tsx
- web/custom-plugins/forecast-of-response/src/components/Plots/ArrowPlots.tsx
- web/custom-plugins/forecast-of-response/src/components/Plots/LinesOverTime.tsx
- web/custom-plugins/forecast-of-response/src/components/Plots/plotUtils.tsx
- web/custom-plugins/forecast-of-response/src/components/Result.tsx
- web/custom-plugins/forecast-of-response/yarn.lock
* display timezone as part of the plot
* display weekday in plot ticks
closes #210
> display timezone and weekday in plot

- .github/workflows/deploy-prod.yml
- .github/workflows/deploy-test.yml
- api/Dockerfile
use version v0.10.1 for api image in deployment
closes #230
> use correct api version
